VentouraMain/Presentation/Ventoura.UI/Areas/VentouraAdmin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Ventoura.Application.Abstractions.Services;
using Ventoura.Application.ViewModels.Tours;
using Ventoura.Domain.Entities;
using Ventoura.Persistence.DAL;
using Ventoura.Persistence.Implementations.Services;

namespace Ventoura.UI.Areas.VentouraAdmin.Controllers
{
    [Area("VentouraAdmin")]
    public class HomeController : Controller
    {
        private readonly AppDbContext _context;

        public HomeController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {

            List<Tour> vm=await _context.Tours.ToListAsync();
            TourGetVM getVM = new TourGetVM
            {
                Capacity = vm.Capacity,

            };
            return View(getVM);
        } 
    }

}

VentouraMain/Presentation/Ventoura.UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Ventoura.Application.Abstractions.Services;
using Ventoura.Domain.Exceptions;

namespace Ventoura.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ITourService _tourService;

        public HomeController(ITourService tourService)
        {
            _tourService = tourService;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _tourService.GetAllAsyncForHome());
        }
        public async Task<IActionResult> Details(int id)
        {
			if (id <= 0) throw new WrongRequestException("Invalid request. Please provide a valid request");
            var tour = await _tourService.GetByIdAsync(id);
			if (tour == null)
			{
				ModelState.AddModelError(string.Empty, "The product you are looking for is no longer available");
				return View("Error");
			}
            return View(await _tourService.GetByIdAsync(id)); 
        } 
    }
}

VentouraMain/Presentation/Ventoura.UI/Controllers/TourController.cs
using Microsoft.AspNetCore.Mvc;
using Ventoura.Application.Abstractions.Services;

namespace Ventoura.UI.Controllers
{
    public class TourController : Controller
    {
        private readonly ITourService _service;
        public TourController(ITourService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index(int page = 1, int take = 4,int order=1)
        {
            return View(await _service.GetAllAsync(page, take,order));
        } 
	}
}

VentouraMain/Presentation/Ventoura.UI/Views/Home/Index.cshtml
@using Ventoura.Application.ViewModels.Pagination;
@using Ventoura.Application.ViewModels.Tours

@model PaginationVM<TourItemVM>
<main> 
    <section class="header-video">
        <div id="hero_video">
            <div class="opacity-mask" data-opacity-mask="rgba(0, 0, 0, 0.6)">
                <div class="intro_title">
                    <h3 class="animated fadeInDown">Affordable Paris tours</h3>
                    <p class="animated fadeInDown">City Tours / Tour Tickets / Tour Guides</p>
                    <a asp-action="Index" asp-controller="Tour" class="animated fadeInUp button_intro">View Tours</a>
                    <a href="#" class="animated fadeInUp button_intro outline hidden-sm hidden-xs">View Hotels</a>
                </div>
            </div>
        </div>
        <img src="~/main/img/video_fix.png" alt="" class="header-video--media" data-video-src="" data-teaser-source="main/video/Paris" data-provider="" data-video-width="854" data-video-height="480">
    </section>
    <div class="white_bg">
        <div class="container margin_60">
            <div class="row small-gutters categories_grid">
                <div class="col-sm-12 col-md-6">
                    <a href="all_tours_list.html">
                        <img src="~/rev-slider-files/assets/img_cat_home_1.jpg" alt="" class="img-fluid">
                        <div class="wrapper">
                            <h2>Special Offers</h2>
                            <p>1150 Locations</p>
                        </div>
                    </a>
                </div>
                <div class="col-sm-12 col-md-6">
                    <div class="row small-gutters mt-md-0 mt-sm-2">
                        <div class="col-sm-6">
                            <a href="all_tours_list.html">
                                <img src="~/rev-slider-files/assets/img_cat_home_2.jpg" alt="" class="img-fluid">
                                <div class="wrapper">
                                    <h2>Tours</h2>
                                    <p>800 Locations</p>
                                </div>
                            </a>
                        </div>
                        <div class="col-sm-6">
                            <a href="all_hotels_list.html">
                                <img src="~/rev-slider-files/assets/img_cat_home_3.jpg" alt="" class="img-fluid">
                                <div class="wrapper">
                                    <h2>Hotels</h2>
                                    <p>650 Locations</p>
                                </div>
                            </a>
                        </div>
                        <div class="col-sm-12 mt-sm-2">
                            <a href="all_restaurants_list.html">
                                <img src="~/rev-slider-files/assets/img_cat_home_4.jpg" alt="" class="img-fluid">
                                <div class="wrapper">
                                    <h2>Restaurants</h2>
                                    <p>1132 Locations</p>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <!--/categories_grid-->
        </div>
        <!-- /container -->
    </div>
    <!-- /white_bg -->

    <div class="container margin_60">

        <div class="main_title">
            <h2> <span>Our</span> Tours</h2>
            <p>Enjoy Ventoura's Tours, Enjoy life!'</p>
        </div>

        <div class="owl-carousel owl-theme list_carousel add_bottom_30">
            @foreach (var item in Model.Items)
            {
                 <div class="item"> 
                    <div class="tour_container">
                        <div class="img_container">
                            <a asp-action="Details" asp-controller="Home" asp-route-id="@item.Id">
                                <img src="~/rev-slider-files/assets/@item.TourImages.FirstOrDefault(c=>c.IsPrimary==true).Url" width="800" height="533" class="img-fluid" alt="image">
                                <div class="short_info">
                                    <span class="CatName">@item.Category.Name</span>
                                   <span class="price"><sup>$</sup>@item.Price</span>
                                </div>
                            </a>
                        </div>
                        <div class="tour_title">    
                            <h3><strong>@item.Name</strong></h3>
                            <div class="rating">
                                <i class="icon-smile voted"></i><i class="icon-smile voted"></i><i class="icon-smile voted"></i><i class="icon-smile voted"></i><i class="icon-smile"></i><small>(75)</small>
                            </div>  
                            <div class="wishlist">
                                <a class="tooltip_flip tooltip-effect-1" asp-action="AddBasket" asp-controller="Basket" asp-route-id="@item.Id">+<span class="tooltip-content-flip"><span class="tooltip-back">Add to Basket</span></span></a>
                            </div> 
                            <!-- End wish list-->
                        </div>
                    </div>
                    <!-- End box tour -->
                </div>
                
            }
        </div>
        <!-- /carousel -->
        <p class="text-center add_bottom_30">
            <a href="all_tours_list.html" class="btn_1">View all Tours</a>
        </p>
       
    </div>
    <!-- End container -->

    <div class="white_bg">
        <div class="container margin_60">
            <div class="main_title">
                <h2>Plan <span>Your Tour</span> Easly</h2>
                <p>
                    Quisque at tortor a libero posuere laoreet vitae sed arcu. Curabitur consequat.
                </p>
            </div>
            <div class="row feature_home_2">
                <div class="col-md-4 text-center">
                    <img src="~/rev-slider-files/assets/adventure_icon_1.svg" alt="" width="75" height="75">
                    <h3>Itineraries studied in detail</h3>
                    <p>Suscipit invenire petentium per in. Ne magna assueverit vel. Vix movet perfecto facilisis in, ius ad maiorum corrumpit, his esse docendi in.</p>
                </div>
                <div class="col-md-4 text-center">
                    <img src="~/rev-slider-files/assets/adventure_icon_2.svg" alt="" width="75" height="75">
                    <h3>Room and food included</h3>
                    <p> Cum accusam voluptatibus at, et eum fuisset sententiae. Postulant tractatos ius an, in vis fabulas percipitur, est audiam phaedrum electram ex.</p>
                </div>
                <div class="col-md-4 text-center">
                    <img src="~/rev-slider-files/assets/adventure_icon_3.svg" alt="" width="75" height="75">
                    <h3>Everything organized</h3>
                    <p>Integre vivendo percipitur eam in, graece suavitate cu vel. Per inani persius accumsan no. An case duis option est, pro ad fastidii contentiones.</p>
                </div>
            </div>

           
            <!-- /banner_2 -->

        </div>
        <!-- End container -->
    </div>
    <!-- End white_bg -->

    <div class="container margin_60">
        <div class="main_title">
            <h2>Lates <span>Blog</span> News</h2>
            <p>Quisque at tortor a libero posuere laoreet vitae sed arcu. Curabitur consequat.</p>
        </div>

        <div class="row">
            <div class="col-lg-6">
                <a class="box_news" href="blog.html">
                    <figure>
                        <img src="~/rev-slider-files/assets/news_home_1.jpg" alt="">
                        <figcaption><strong>28</strong>Dec</figcaption>
                    </figure>
                    <ul>
                        <li>Mark Twain</li>
                        <li>20.11.2017</li>
                    </ul>
                    <h4>Pri oportere scribentur eu</h4>
                    <p>Cu eum alia elit, usu in eius appareat, deleniti sapientem honestatis eos ex. In ius esse ullum vidisse....</p>
                </a>
            </div>
            <!-- /box_news -->
            <div class="col-lg-6">
                <a class="box_news" href="blog.html">
                    <figure>
                        <img src="~/rev-slider-files/assets/news_home_2.jpg" alt="">
                        <figcaption><strong>28</strong>Dec</figcaption>
                    </figure>
                    <ul>
                        <li>Jhon Doe</li>
                        <li>20.11.2017</li>
                    </ul>
                    <h4>Duo eius postea suscipit ad</h4>
                    <p>Cu eum alia elit, usu in eius appareat, deleniti sapientem honestatis eos ex. In ius esse ullum vidisse....</p>
                </a>
            </div>
            <!-- /box_news -->
            <div class="col-lg-6">
                <a class="box_news" href="blog.html">
                    <figure>
                        <img src="~/rev-slider-files/assets/news_home_3.jpg" alt="">
                        <figcaption><strong>28</strong>Dec</figcaption>
                    </figure>
                    <ul>
                        <li>Luca Robinson</li>
                        <li>20.11.2017</li>
                    </ul>
                    <h4>Elitr mandamus cu has</h4>
                    <p>Cu eum alia elit, usu in eius appareat, deleniti sapientem honestatis eos ex. In ius esse ullum vidisse....</p>
                </a>
            </div>
            <!-- /box_news -->
            <div class="col-lg-6">
                <a class="box_news" href="blog.html">
                    <figure>
                        <img src="~/rev-slider-files/assets/news_home_4.jpg" alt="">
                        <figcaption><strong>28</strong>Dec</figcaption>
                    </figure>
                    <ul>
                        <li>Paula Rodrigez</li>
                        <li>20.11.2017</li>
                    </ul>
                    <h4>Id est adhuc ignota delenit</h4>
                    <p>Cu eum alia elit, usu in eius appareat, deleniti sapientem honestatis eos ex. In ius esse ullum vidisse....</p>
                </a>
            </div>
            <!-- /box_news -->
        </div>
        <!-- /row -->
        <p class="btn_home_align"><a href="blog.html" class="btn_1 rounded">View all news</a></p>
    </div>
    <!-- End container -->
</main>
<!-- End main -->
<!-- Common scripts -->
<script src="~/main/js/jquery-3.6.0.min.js"></script>
<script src="~/main/js/common_scripts_min.js"></script>
<script src="~/main/js/functions.js"></script>
<!-- Video header scripts -->
<script src="~/main/js/modernizr.js"></script>
<script src="~/main/js/video_header.js"></script>
<script>
    HeaderVideo.init({
        container: $('.header-video'),
        header: $('.header-video--media'),
        videoTrigger: $("#video-trigger"),
        autoPlayVideo: false
    });
</script>